### ISSUE TITLE
Kiali Credential not working 

### ISSUE THREAD

**Issue by alonsoir** [apssouza22/service-mesh-istio#1]
I am running Docker Desktop with Kubernetes In OS X 10.15.4, no minikube, when I try to run Kiali with default credential (admin/admin) I cannot continue.

  The Kiali secret is missing. Users are prohibited from accessing Kiali until an administrator creates a valid secret. Please refer to the Kiali documentation for more details.

What should I do? 

Thank you.

**Comment by apssouza22** [comment]
Have watched the videos? Maybe you can get some hit from those.

Anyway, make sure you have run this https://github.com/apssouza22/service-mesh-istio/blob/master/3-kiali-secret.yaml

Good look
